services:
  pg:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=upload
    ports:
      - 5432:5432
    volumes:
      - './docker:/docker-entrypoint-initdb.d'